mode: required
method: netinstall-select

labels:
    step: "Desktop"
    step[ru]: "Рабочий стол"

items:
    - id: KDE-Desktop
      name: "KDE Plasma"
      description: "KDE Plasma — красивое и мощное окружение рабочего стола для Equestria OS."
      description[ru]: "KDE Plasma — красивое и мощное окружение рабочего стола для Equestria OS."
      screenshot: "/etc/calamares/images/plasma.jpg"
