i18n:
     name: "Preparing filesystem paths..."
dontChroot: true
timeout: 30
script:
    - "-mkdir -p /run/archiso/bootmnt/arch/x86_64"
    - "-ln -sf /run/archiso/copytoram/airootfs.sfs /run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
