dontChroot: false
timeout: 600
script:
    # 1. Монтируем ESP, используя свежий сгенерированный fstab
    - "-mount /boot/efi"

    # 2. Обязательно монтируем efivarfs, иначе BIOS не обновится!
    - "-mount -t efivarfs efivarfs /sys/firmware/efi/efivars"

    # 3. Ставим GRUB
    - "grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=EquestriaOS --recheck"

    # 4. Тот самый фикс для Asus и USB-дисков
    - "mkdir -p /boot/efi/EFI/BOOT"
    - "cp -f /boot/efi/EFI/EquestriaOS/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI"

    # 5. Генерируем конфиг
    - "grub-mkconfig -o /boot/grub/grub.cfg"

i18n:
     name: "Installing GRUB bootloader..."
