---
script:
 - command: "pacman-key --init"
   timeout: 1200
 - command: "pacman-key --populate archlinux"
   timeout: 300
 - command: "pacman-key --populate equestria-os"
   timeout: 300

i18n:
 name: "Initializing Equestria OS package manager keyring..."
