dontChroot: true
timeout: 300
script:
    - "-mkdir -p ${ROOT}/boot/efi/EFI/BOOT"
    - "-cp -f ${ROOT}/boot/efi/EFI/EquestriaOS/grubx64.efi ${ROOT}/boot/efi/EFI/BOOT/BOOTX64.EFI"
i18n:
     name: "Weaving fallback boot magic..."
