dontChroot: false
timeout: 30
script:
    # Переименовываем метку корневого раздела из "root" в "Equestria OS"
    - "bash -c 'DEV=$(findmnt -n -o SOURCE /); FSTYPE=$(findmnt -n -o FSTYPE /); case \"$$FSTYPE\" in ext4|ext3|ext2) e2label \"$$DEV\" \"Equestria OS\";; btrfs) btrfs filesystem label / \"Equestria OS\";; xfs) xfs_admin -L \"Equestria OS\" \"$$DEV\";; esac; exit 0'"
i18n:
     name: "Setting disk label..."
