dontChroot: true
timeout: 300
script:
    # 1. Фиксим конфиги для сборки ядра
    - "-rm -f ${ROOT}/etc/mkinitcpio.conf.d/archiso.conf"
    - "-sed -i 's/archiso/default/g' ${ROOT}/etc/mkinitcpio.d/linux.preset"
    - "-sed -i 's|/etc/mkinitcpio.conf.d/default.conf|/etc/mkinitcpio.conf|g' ${ROOT}/etc/mkinitcpio.d/linux.preset"

    # 2. Копируем ядро на место
    - "-cp -f ${ROOT}/usr/lib/modules/*/vmlinuz ${ROOT}/boot/vmlinuz-linux"

    # 3. УДАЛЯЕМ МУСОР: пакет флешки и сам установщик Calamares
    - "-pacman --root ${ROOT} -Rns --noconfirm mkinitcpio-archiso calamares"

    # 4. УБИВАЕМ LIVEUSER: жёстко вычищаем его и его домашнюю папку из новой системы
    - "-chroot ${ROOT} userdel -f -r liveuser || true"

i18n:
     name: "Fixing kernel and cleaning up the system..."
