dontChroot: false
timeout: 120
script:
    - "-userdel -f -r liveuser"
    - "-rm -f /etc/skel/Desktop/install-equestria.desktop"
    - "-rm -f /usr/share/applications/install-equestria.desktop"
    - "-rm -f /usr/local/bin/install-equestria.sh"
    - "-rm -f /home/*/Desktop/install-equestria.desktop"
i18n:
     name: "Cleaning up installer files..."
