dontChroot: true
timeout: 300
script:
    - "-rm -f ${ROOT}/etc/mkinitcpio.conf.d/archiso.conf"
    - "-sed -i 's/archiso/default/g' ${ROOT}/etc/mkinitcpio.d/linux.preset"
    - "-sed -i 's|/etc/mkinitcpio.conf.d/default.conf|/etc/mkinitcpio.conf|g' ${ROOT}/etc/mkinitcpio.d/linux.preset"
    - "-cp -f ${ROOT}/usr/lib/modules/*/vmlinuz ${ROOT}/boot/vmlinuz-linux"
    - "-pacman --root ${ROOT} -Rdd --noconfirm mkinitcpio-archiso"
i18n:
     name: "Fixing kernel for the target system..."
