options iwlwifi power_save=0
options iwlwifi disable_11ax=1
options iwlwifi 11n_disable=8
options iwlmvm power_scheme=1
options iwlwifi uapsd_disable=1

# Fix slow speed and drops for Intel CNVi WiFi
options iwlwifi disable_11ax=Y
options iwlwifi bt_coex_active=N
