modules-search: [ local ]

instances:
- id:       offline
  module:   packages
  config:   packages_offline.conf
- id:       offline
  module:   welcome
  config:   welcome_offline.conf
- id:       copyfiles
  module:   shellprocess
  config:   shellprocess_copyfiles.conf
- id:       removeucode
  module:   shellprocess
  config:   shellprocess_removeucode.conf
# Добавляем наш скрипт для починки copytoram:
- id:       fixpaths
  module:   shellprocess
  config:   shellprocess_fixpaths.conf
# РЕГИСТРИРУЕМ ФИКС ЯДРА:
- id:       fixkernel
  module:   shellprocess
  config:   shellprocess_fixkernel.conf
- id:       installgrub
  module:   shellprocess
  config:   shellprocess_installgrub.conf

- id:       cleanup
  module:   shellprocess
  config:   shellprocess_cleanup.conf

sequence:
- show:
  - welcome@offline
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - shellprocess@fixpaths  # <-- Фиксит ошибку "airootfs.sfs не существует"
  - unpackfs
  - shellprocess@fixkernel
  - machineid
  - fstab
  - locale
  - keyboard
  - removeuser
  - users
  - networkcfg
  - displaymanager
  - hwclock
  - initcpio               # <-- КРИТИЧНО: собирает образ ядра Linux
  - grubcfg
  - shellprocess@installgrub
  - services-systemd
  - preservefiles
  - shellprocess@cleanup
  - umount
- show:
  - finished

branding: equestria-os
prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
