modules-search: [ local ]

instances:
- id:       offline
  module:   welcome
  config:   welcome_offline.conf

- id:       fixpaths
  module:   shellprocess
  config:   shellprocess@fixpaths.conf

- id:       fixkernel
  module:   shellprocess
  config:   shellprocess_fixkernel.conf

- id:       installgrub
  module:   shellprocess
  config:   shellprocess_installgrub.conf


- id:       gpusetup
  module:   shellprocess
  config:   shellprocess_gpusetup.conf

- id:       cleanup
  module:   shellprocess
  config:   shellprocess_cleanup.conf

- id:       removeucode
  module:   shellprocess
  config:   shellprocess_removeucode.conf

- id:       keyring
  module:   shellprocess
  config:   shellprocess_keyring.conf

- id:       setlabel
  module:   shellprocess
  config:   shellprocess_setlabel.conf

- id:       fixkxkb
  module:   shellprocess
  config:   shellprocess_fixkxkb.conf

- id:       localegen
  module:   shellprocess
  config:   shellprocess_localegen.conf

sequence:
- show:
  - welcome@offline
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - shellprocess@fixpaths
  - unpackfs
  - shellprocess@keyring
  - shellprocess@setlabel
  - machineid
  - fstab
  - locale
  - shellprocess@localegen
  - keyboard
  - shellprocess@fixkernel
  - shellprocess@fixkxkb
  - shellprocess@gpusetup
  - users
  - removeuser
  - shellprocess@cleanup
  - networkcfg
  - displaymanager
  - hwclock
  - initcpio
  - grubcfg
  - shellprocess@removeucode
  - shellprocess@installgrub
  - services-systemd
  - preservefiles
  - umount
- show:
  - finished

branding: equestria-os
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
