modules-search: [ local ]

instances:
- id:       offline
  module:   packages
  config:   packages_offline.conf
- id:       offline
  module:   welcome
  config:   welcome_offline.conf
- id:       copyfiles
  module:   shellprocess
  config:   shellprocess_copyfiles.conf
- id:       removeucode
  module:   shellprocess
  config:   shellprocess_removeucode.conf

sequence:
- show:
  - welcome@offline
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - removeuser
  - users
  - networkcfg
  - displaymanager
  - hwclock
  - grubcfg
  - bootloader
  - services-systemd
  - preservefiles
  - umount
- show:
  - finished

branding: equestria-os
prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
